### ISSUE TITLE
Provide docs for CLI

### ISSUE THREAD

**Issue by Nitecon** [wellington/wellington#170]
Seems there is documentation on using both gulp / grunt but there appears to be no documentation on using the CLI application (wt)

Currently looking at tests within the application I would expect that the following works without issues:

`wt compile somefile.scss`

However the above line generates the output on stdout which is fine but is followed by a stack trace error as seen below:

		2016/01/04 15:56:39 Compilation took: 3.864815ms
		panic: interface conversion: *spritewell.SafeImageMap is not payload.Payloader: missing method ForEach

		goroutine 1 [running]:
		github.com/wellington/wellington/payload.Sprite(0x7f77abe4d8d0, 0xc8200155f0, 0x0, 0x0)
			/data/apps/go/src/github.com/wellington/wellington/payload/payload.go:34 +0xbf
		main.run(0xc82001a180, 0x1, 0x8, 0xc820012bc0, 0xc82000b5e0)
			/data/apps/go/src/github.com/wellington/wellington/wt/main.go:419 +0x56b
		main.Compile(0xe1e720, 0xc82001a180, 0x1, 0x8)
			/data/apps/go/src/github.com/wellington/wellington/wt/main.go:373 +0xee
		github.com/spf13/cobra.(*Command).execute(0xe1e720, 0xc8200b8000, 0x8, 0xe, 0x0, 0x0)
			/data/apps/go/src/github.com/spf13/cobra/command.go:569 +0x869
		github.com/spf13/cobra.(*Command).ExecuteC(0xe1ed20, 0xe1e720, 0x0, 0x0)
			/data/apps/go/src/github.com/spf13/cobra/command.go:656 +0x56b
		github.com/spf13/cobra.(*Command).Execute(0xe1ed20, 0x0, 0x0)
			/data/apps/go/src/github.com/spf13/cobra/command.go:615 +0x2d
		main.main()
			/data/apps/go/src/github.com/wellington/wellington/wt/main.go:175 +0x2d

		goroutine 17 [syscall, locked to thread]:
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

Expected behavior:
- Provide documentation on how to use wt client application (as it requires different options from standard sass cli's)
- Fix errors, as this indicates a serious issue.

**Comment by drewwells** [comment]
There's been some refactoring on master, it looks like you have a stale spritewell. Did you build this with godep? If not, `go get -u github.com/wellington/spritewell` and let me know about the stacktrace.

I agree the docs are limited, this is all that's available in the readme: https://github.com/wellington/wellington#available-commands. I'm open to PR if you have ideas for how to best detail this. Maybe the available commands section lets you know that stdout is used by default.

**Comment by Nitecon** [comment]
I did the updates as below but still got the stack trace:

Updated with:
`go get -u github.com/wellington/spritewell`
`go get -u github.com/wellington/wellington`
`go install github.com/wellington/wellington/wt`

Then validated it was an updated binary with `ls -al $GOPATH/bin/`
`-rwxr-xr-x 1 whatting users 23578304 Jan  4 16:21 wt`

Command that was run: `wt compile test.scss`

Output:

		2016/01/04 16:24:59 Compilation took: 4.172255ms
		panic: interface conversion: *spritewell.SafeImageMap is not payload.Payloader: missing method ForEach

		goroutine 1 [running]:
		github.com/wellington/wellington/payload.Sprite(0x7f7b2442e8d0, 0xc82000b620, 0x0, 0x0)
			/data/apps/go/src/github.com/wellington/wellington/payload/payload.go:34 +0xbf
		main.run(0xc8200af1a0, 0x1, 0x1, 0xc820012b00, 0xc82009d400)
			/data/apps/go/src/github.com/wellington/wellington/wt/main.go:419 +0x56b
		main.Compile(0xe1e720, 0xc8200af1a0, 0x1, 0x1)
			/data/apps/go/src/github.com/wellington/wellington/wt/main.go:373 +0xee
		github.com/spf13/cobra.(*Command).execute(0xe1e720, 0xc8200af130, 0x1, 0x1, 0x0, 0x0)
			/data/apps/go/src/github.com/spf13/cobra/command.go:569 +0x869
		github.com/spf13/cobra.(*Command).ExecuteC(0xe1ed20, 0xe1e720, 0x0, 0x0)
			/data/apps/go/src/github.com/spf13/cobra/command.go:656 +0x56b
		github.com/spf13/cobra.(*Command).Execute(0xe1ed20, 0x0, 0x0)
			/data/apps/go/src/github.com/spf13/cobra/command.go:615 +0x2d
		main.main()
			/data/apps/go/src/github.com/wellington/wellington/wt/main.go:175 +0x2d

		goroutine 17 [syscall, locked to thread]:
		runtime.goexit()
			/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1


PS: When I get some free time later this week I'll work on PR for docs.

**Comment by drewwells** [comment]
Agh, you are right. The updated spritewell was only in the vendored folder. This is fixed now. Another `go get -u github.com/wellington/spritewell` will fix the stacktrace.

On the topic of the default compile command, stdout is insufficient for most sprite methods. I opened #171 to add better error messages around those.
